### ISSUE TITLE
No sound on Dingoo a320's opendingux 

### ISSUE THREAD

**Issue by abrusco** [irixxxx/picodrive#39]
Irixxxx,

I managed to run Picodrive 1.98 (PicoDrive-dge_1.98.zip) on OpenDingux from Dingoo A320. But it's completely muted. 

Version 1.91 works normally

**Comment by irixxxx** [comment]
AFAICT it's a problem of uClibc, which is the base C library used in (open)dingux. There seems to be a problem having a different version of the SDL shared library in the OS than what was used in the toolchain I used to make the build.

I'm not really sure this can be fixed in a satisfactory manner, apart from making a different build for all the toolchains floating around (I used the latest legacy dingux toolchain I could find for the dge, IIRC from 2012 or 2013), which might be a bit over the top for me.

If you can make your own builds make a picodrive build with the toolchain associated with the OS version installed on your A320 (look at tools/release.sh for "build instructions" :-D), and report back if that is working for you. A pointer to the binary toolchain install would be useful that case.

If somebody would supply tested (!) builds with other toolchains I would be willing to put them up on the release page ;-)

**Comment by abrusco** [comment]
Legacy Opendingux on a320 only suport pge packages.
I found the latest version of the source code and the latest compiled version that works correctly on the A320. 
https://github.com/notaz/picodrive/releases/
https://pyra-handheld.com/boards/resources/picodrive-1-93-opendingux.4558/
![image](https://user-images.githubusercontent.com/8458577/137138601-c7dae47a-4ef7-48c5-8c7e-1b441ce60673.png)

Would it be possible to use the same compilation parameters to generate a new compatible version? 
ps. Sorry, English isn't my first language. Feel free to correct me.

**Comment by abrusco** [comment]
> 
> 
> Hmm, it's probably not a question of parameters,but a question of the toolchain used for compiling. Do you have a corresponding toolchain for the a320 opendingux? In that case try compiling the current picodrive with that.

I tried to download the latest version of Toolchain but apparently all sites are down. 
http://www.treewalker.org/opendingux/
http://www.treewalker.org/opendingux/opendingux-toolchain.2012-06-16.tar.bz2
http://prizma.bmstu.ru/~exmortis/gcw0-toolchain-cygwin.2012-10-21.tar.gz

If you can find it let me know I'm trying to build it. Thank you1

**Comment by irixxxx** [comment]
hmm, I used a 2012 toolchain for this. It might well be that toolchain you referenced :-/
The only slightly obscure option in my release build is "-mabicalls", which IIRC is needed for rzx50 which is the only dingux device from that age I have. You could try compiling without that and see if it works better.

**Comment by irixxxx** [comment]
IIRC there's a cygwin version for windows as well. I never used it, though.

abrusco ***@***.***> schrieb am Fr., 15. Okt. 2021, 02:18:

**Comment by irixxxx** [comment]
Is this problem still there with the 1.99 release files?

**Comment by abrusco** [comment]
> 

Sound now works on DINGUX *And* Opendingux!!!!  Great!!!
