### ISSUE TITLE
Buttons don´t work on miyoo realease

### ISSUE THREAD

**Issue by abrusco** [irixxxx/picodrive#54]
Hi!! 

I'm testing the Miyoo binary version. The emulator normally loads the game but only the dpad works  no buttons work .

I'm testing it on PowKiddy Q90 of MiyooCFW 1.3.3

Thanks!

**Comment by freq-mod** [comment]
Delete the config file (issue #42)

**Comment by irixxxx** [comment]
Is this still an issue, or can I close this?

**Comment by freq-mod** [comment]
maybe close, but pin it?
Next release, I will add the config file into the archive with binary.

**Comment by abrusco** [comment]
I just delete the .picodrive folder on main/.picodrive, remap buttons and works!

Thanks!
![image](https://user-images.githubusercontent.com/8458577/146064320-e723f484-7036-44f3-a782-83162ddb6037.png)

**Comment by irixxxx** [comment]
I have already put a note and a link to this issue on the release page. I sincerely hope people are reading before they download...

**Comment by RocknRace** [comment]
Picodrive 1.99 controls and commands work in Powkiddy's original NxHope. So instead of delet the Config script, I Copied and Pasted  the binds keys contained in NxHope to work correctly in .Picodrive hiden folder -> Config script,  Under Miyoo when using the Powkiddy  Q9:

 This bring me free to point with the D-Pad and  using  Start and Select buttons to Choose.

D-Pad = All arrows
Start = Return (Enter)
Select = Escape
_______________________________________________

This is the alteration on the Config Script.  bringing this Binds from early Picodrive version on the NxHope

binddev = sdl:keys
bind backspace = player1 Z
bind tab = player1 Y
bind tab = Save State
bind return = player1 START
bind escape = player1 MODE
bind escape = Load State
bind space = player1 A
bind up = player1 UP
bind down = player1 DOWN
bind right = player1 RIGHT
bind left = player1 LEFT
bind f1 = Reset Game
bind f4 = Prev Save Slot
bind f5 = Next Save Slot
bind f6 = Switch Renderer
bind f7 = Pico Prev page
bind f8 = Pico Next page
bind f9 = Pico Switch input
bind f10 = Fast forward
bind left shift = player1 B
bind left shift = player1 X
bind right ctrl = Enter Menu
bind left ctrl = player1 B turbo
bind left alt = player1 C
Sound Volume = 90

![Picodrive 199 under Powkiddy Miyoo](https://github.com/irixxxx/picodrive/assets/140572041/cc37bd78-4ba2-4580-a246-a4d8f68f613e)
