### ISSUE TITLE
Vectorman 1 and 2 crash on startup

### ISSUE THREAD

**Issue by n1ghttrap** [irixxxx/picodrive#69]
Latest nightly RA and core. Reset core config to defaults, run ahead off, tried 'good', 'accurate', and 'fast' renderers. 1 freezes at the Sega logo instantly, 2 black-screens, regardless of ROM region/region setting. Dynamic recompiler on and off.

**Comment by n1ghttrap** [comment]
These are fine in the pre-fork standalone.

**Comment by DrUm78** [comment]
Same for me on armv7 both with Cyclone/DrZ80 and Fame/CZ80.

**Comment by DrUm78** [comment]
It works with [official 1.99](https://github.com/irixxxx/picodrive/commit/404af43ddce805aafa55710f54c36be68e06e225) on MIPS3r2 (RG350) though, so it reduces the commits to investigate.

**Comment by irixxxx** [comment]
fixed with 72c2a04

**Comment by n1ghttrap** [comment]
Is there a github specifically for the libretro core, or do you oversee it?  Do you know when it might get updated there?

**Comment by irixxxx** [comment]
yes, there's libretro/picodrive. I have rights for that and do regular merges from my repo... well, more or less regular fwiw. I'm trying to keep monthly to bimonthly schedule for this. I'm not doing this more often since I test the basic functionality and the bug fixes with retroarch before merging, which takes some time.
The last merge was unfortunately just days ago, though :-/
