### ISSUE TITLE
Add borders (overscan)

### ISSUE THREAD

**Issue by ghost** [irixxxx/picodrive#81]
@irixxxx can you please add "Borders" option to show entire overscan empty blank area 320x240 resolution in SG-1000/SC-3000, Mark III/Master System/SMS II, Game Gear and Genesis/MegaDrive/CD/32X
![STH](https://user-images.githubusercontent.com/113312388/193476256-597ddb60-f0f8-4d3e-9549-e0af520d282d.png)
![Alex Kidd No Miracle World](https://user-images.githubusercontent.com/113312388/193476258-89b1daaa-239d-446b-8325-8991258c60a7.png)

**Comment by irixxxx** [comment]
Out of curiosity, why would you want that?

The problem is that all the internal buffering is hammered fixed at 320x240 since picodrive's inception. That's what most portable consoles with a 4:3 display had at those times, and often still have. Changing it would be a helluva lot of work. There must be a really good reason besides esthetics to even think about that.
An easier thing would probably be to blow the current rendered output up to 320x240 by filling everything not filled by the frame renderer with the background color. It may look alike but wouldn't emulate anything in that faked border area, besides not displaying any left and right border for output scaled to correct aspect ratio which always has 320 px width.

**Comment by LeopoldCraft0055** [comment]
Yes

**Comment by LeopoldCraft0055** [comment]
It isn't faked border area. I use screenshot on Gens Plus emulator

**Comment by irixxxx** [comment]
See #108 which has some images to illustrate the request better.
